### ISSUE TITLE
Add Support for Internationalization (i18n)

### ISSUE THREAD

**Issue by sumn2u** [sumn2u/deep-waste-app#6]
The plan is to add a way to support internationalization (i18n) in our application. The language support will help reach more people and lessen the boundaries.

## Description

To broaden the reach and inclusivity of our  application, we propose implementing internationalization (i18n) support. This feature will allow users from different linguistic backgrounds to access and use the application in their preferred language. By doing so, we can enhance user experience and make our project more accessible globally.

## Goals

1. Identify key areas of the application that require translation.
2. Implement a system for managing multiple languages.
3. Ensure that the application can dynamically switch between languages based on user preference.
4. Provide documentation and guidelines for contributing translations.

## Implementation Steps

1. **Language Files**: Create separate language files for each supported language.
    - Use the `intl` package for managing translations.
    - Example structure:
      ```dart
      // lib/l10n/intl_en.arb
      {
        "welcome": "Welcome",
        "login": "Login"
      }

      // lib/l10n/intl_es.arb
      {
        "welcome": "Bienvenido",
        "login": "Iniciar sesión"
      }
      ```

2. **Language Switcher**: Develop a user interface component that allows users to select their preferred language.
    - This can be a dropdown menu, toggle switch, or similar UI element.

3. **Dynamic Content Loading**: Ensure that the application can load and display the correct language content dynamically.
    - Use the `intl` and `flutter_localizations` packages to handle localization.

4. **Translation Management**: Set up a process for managing and updating translations.
    - Consider using a translation management platform (e.g., Crowdin, Transifex) for community contributions.

5. **Testing**: Thoroughly test the implementation with multiple languages to ensure proper functionality and display.

6. **Documentation**: Update the project documentation to include instructions on how to add new languages and contribute translations.

## Additional Notes

- Prioritize support for languages based on user demographics and feedback.
- Engage the community to help with translations and ensure accuracy.
- Consider cultural nuances and context in translations to maintain the integrity of the content.

## References

- [Flutter Internationalization](https://flutter.dev/docs/development/accessibility-and-localization/internationalization)
- [intl package](https://pub.dev/packages/intl)
- [flutter_localizations package](https://pub.dev/packages/flutter_localizations)
- [Crowdin](https://crowdin.com/)
- [Transifex](https://www.transifex.com/)

## Tasks

- [ ] Identify key areas of the application for translation
- [ ] Implement language file structure using the `intl` package
- [ ] Develop language switcher component
- [ ] Integrate dynamic content loading with `intl` and `flutter_localizations`
- [ ] Set up translation management process
- [ ] Conduct testing with multiple languages
- [ ] Update project documentation

**Comment by mohitrajsinha** [comment]
Hi @sumn2u . Please assign this issue to me.

**Comment by sumn2u** [comment]
> Hi @sumn2u . Please assign this issue to me.

Sure.
